# By default, Docker names project directory name, names built images {project}_{service}, and names each container {project}_{service}_{index}
version: "3.8"

services:   

    demucs:
        build:
            context: .
            dockerfile: demucs.Dockerfile
        ports:
            - "5001:5001"
        volumes:
            - demucs-models:/data/models
            - demucs-input:/data/input
            - demucs-output:/data/output
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: music

volumes:
    demucs-models:
    demucs-input:
    demucs-output:
    db-data: